import { registerAs } from '@nestjs/config';
import * as process from 'node:process';

export default registerAs('general', () => ({
  CHAPAR_ACTIVE: process.env.CHAPAR_ACTIVE || true,
  CHAPAR_USERNAME: process.env.CHAPAR_USERNAME,
  CHAPAR_PASSWORD: process.env.CHAPAR_PASSWORD,
  THIRD_PARTIES_PROXY: process.env.THIRD_PARTIES_PROXY,
  CHAPAR_API_BASE_URI: process.env.CHAPAR_API_BASE_URI,
  FARAPAYAMAK_CONTACT_US_PHONE_NUMBER:
    process.env.FARAPAYAMAK_CONTACT_US_PHONE_NUMBER,
  FARAPAYAMAK_DELAY_DAYS_TO_WAIT: process.env.FARAPAYAMAK_DELAY_DAYS_TO_WAIT,
  FARAPAYAMAK_TOTAL_SALES_TEXT_CODE:
    process.env.FARAPAYAMAK_TOTAL_SALES_TEXT_CODE,
  FARAPAYAMAK_TOTAL_SALES_TEXT: process.env.FARAPAYAMAK_TOTAL_SALES_TEXT,
  FARAPAYAMAK_SUBMIT_PREORDER_TEXT_CODE:
    process.env.FARAPAYAMAK_SUBMIT_PREORDER_TEXT_CODE,
  FARAPAYAMAK_SUBMIT_PREORDER_TEXT:
    process.env.FARAPAYAMAK_SUBMIT_PREORDER_TEXT,
  FARAPAYAMAK_SEND_PREORDER_ACTIVATION_TEXT_CODE:
    process.env.FARAPAYAMAK_SEND_PREORDER_ACTIVATION_TEXT_CODE,
  FARAPAYAMAK_SEND_PREORDER_ACTIVATION_TEXT:
    process.env.FARAPAYAMAK_SEND_PREORDER_ACTIVATION_TEXT,
  FARAPAYAMAK_TEXT_CODE_NEGOTIATION_MOVE_ALERT:
    process.env.FARAPAYAMAK_TEXT_CODE_NEGOTIATION_MOVE_ALERT,
  FARAPAYAMAK_TEXT_NEGOTIATION_MOVE_ALERT:
    process.env.FARAPAYAMAK_TEXT_NEGOTIATION_MOVE_ALERT,
  FARAPAYAMAK_NEW_USERS_WALLET_CHARGE_TEXT_CODE:
    process.env.FARAPAYAMAK_NEW_USERS_WALLET_CHARGE_TEXT_CODE,
  FARAPAYAMAK_NEW_USERS_WALLET_CHARGE_TEXT:
    process.env.FARAPAYAMAK_NEW_USERS_WALLET_CHARGE_TEXT,
  FARAPAYAMAK_PREORDER_REGISTER_MESSAGE_CODE:
    process.env.FARAPAYAMAK_PREORDER_REGISTER_MESSAGE_CODE,
  FARAPAYAMAK_PREORDER_REGISTER_MESSAGE_TEXT:
    process.env.FARAPAYAMAK_PREORDER_REGISTER_MESSAGE_TEXT,
  FARAPAYAMAK_PREORDER_REMINDER_BEFORE_CODE:
    process.env.FARAPAYAMAK_PREORDER_REMINDER_BEFORE_CODE,
  FARAPAYAMAK_PREORDER_REMINDER_BEFORE_TEXT:
    process.env.FARAPAYAMAK_PREORDER_REMINDER_BEFORE_TEXT,
  FARAPAYAMAK_PREORDER_ON_TURN_DATE_CODE:
    process.env.FARAPAYAMAK_PREORDER_ON_TURN_DATE_CODE,
  FARAPAYAMAK_PREORDER_ON_TURN_DATE_TEXT:
    process.env.FARAPAYAMAK_PREORDER_ON_TURN_DATE_TEXT,
}));
