export const InvoicePaymentType = {
  INVOICE_PAYMENT_TYPE_BANK_GATEWAY: 1,
  INVOICE_PAYMENT_TYPE_MONEY_TRANSFER: 2,
  INVOICE_PAYMENT_TYPE_BY_WALLET: 3,
  INVOICE_PAYMENT_TYPE_BY_CHEQUE: 4,
  INVOICE_PAYMENT_TYPE_CASH_ON_DELIVERY: 5,
  INVOICE_PAYMENT_TYPE_BY_CASH: 6,
  INVOICE_PAYMENT_TYPE_AZKI_GATEWAY: 7,
  INVOICE_PAYMENT_TYPE_EGHTESAD_NOVIN: 8,
  INVOICE_PAYMENT_TYPE_SNAPPPAY_GATEWAY: 9,
  INVOICE_PAYMENT_TYPE_DIGIPAY_CREDIT: 10, // Digipay Installments By Credit
  INVOICE_PAYMENT_TYPE_DIGIPAY_BNPL: 11, // Digipay Buy Now Pay Later(in 1 payment or via 4 installments)
  INVOICE_PAYMENT_TYPE_ZARIN_PLUS: 12,
};
