export const InvoiceStatus = {
  INVOICE_STATUS_INITIATED: 1,
  INVOICE_STATUS_ADDRESS_VALIDATED: 2,
  INVOICE_STATUS_SHIPPING_SELECTED: 3,
  INVOICE_STATUS_PRICE_FINALIZED: 4,
  INVOICE_STATUS_PAYMENT_PENDING: 5,

  INVOICE_STATUS_AWAITING_PROCESS: 7,

  // Newly Added: 2021-01-31 and increased other steps, each step has a on number gap to be able to add some steps between them
  INVOICE_STATUS_CHECKED_BY_SALES_DEPARTMENT: 9,

  INVOICE_STATUS_REFERRED_TO_PRODUCTION_DEPARTMENT: 11,
  INVOICE_STATUS_PREPARING_PRODUCTS: 13,
  INVOICE_STATUS_PRODUCTION_COMPLETED: 15,

  // Newly Added: 2020-12-09 and increased other statuses after this status
  INVOICE_STATUS_RECEIVED_BY_PACKAGING_DEPARTMENT: 17,
  INVOICE_STATUS_READY_TO_SEND_CHAPAR: 19,
  INVOICE_STATUS_READY_TO_SEND_MAHEX: 20,
  INVOICE_STATUS_READY_TO_SEND_GENERAL_EXPRESS: 21,

  INVOICE_STATUS_READY_TO_SEND_TIPAX: 22,
  INVOICE_STATUS_SENT: 23,
  INVOICE_STATUS_DELIVERED: 25,
  INVOICE_STATUS_CANCEL: 27,
  INVOICE_STATUS_RETURN_TO_ORIGIN: 29,
  INVOICE_STATUS_ADDED_TO_DEPOT_INVENTORY: 31,
  INVOICE_STATUS_DAMAGED_DURING_PRODUCTION: 33,
  INVOICE_STATUS_CANCELED_SNAPP_AFTER_RECEIVED_BY_CUSTOMER: 35,
};
