export enum InvoiceStatusEnum {
  INITIATED = 1,
  ADDRESS_VALIDATED = 2,
  SHIPPING_SELECTED = 3,
  PRICE_FINALIZED = 4,
  PAYMENT_PENDING = 5,

  AWAITING_PROCESS = 7,
  CHECKED_BY_SALES_DEPARTMENT = 9,
  REFERRED_TO_PRODUCTION_DEPARTMENT = 11,
  PREPARING_PRODUCTS = 13,
  PRODUCTION_COMPLETED = 15,
  RECEIVED_BY_PACKAGING_DEPARTMENT = 17,
  READY_TO_SEND_CHAPAR = 19,
  READY_TO_SEND_MAHEX = 20,
  READY_TO_SEND_GENERAL_EXPRESS = 21,
  READY_TO_SEND_TIPAX = 22,
  SENT = 23,
  DELIVERED = 25,
  CANCEL = 27,
  RETURN_TO_ORIGIN = 29,
  ADDED_TO_DEPOT_INVENTORY = 31,
  DAMAGED_DURING_PRODUCTION = 33,
  CANCELED_SNAPP_AFTER_RECEIVED_BY_CUSTOMER = 35,
}

export const NOT_SENT_INVOICE_STATUSES: InvoiceStatusEnum[] = [
  InvoiceStatusEnum.AWAITING_PROCESS,
  InvoiceStatusEnum.CHECKED_BY_SALES_DEPARTMENT,
  InvoiceStatusEnum.REFERRED_TO_PRODUCTION_DEPARTMENT,
  InvoiceStatusEnum.PREPARING_PRODUCTS,
  InvoiceStatusEnum.PRODUCTION_COMPLETED,
  InvoiceStatusEnum.RECEIVED_BY_PACKAGING_DEPARTMENT,
  InvoiceStatusEnum.READY_TO_SEND_CHAPAR,
  InvoiceStatusEnum.READY_TO_SEND_MAHEX,
  InvoiceStatusEnum.READY_TO_SEND_GENERAL_EXPRESS,
  InvoiceStatusEnum.READY_TO_SEND_TIPAX,
];

export const READY_TO_SEND_INVOICE_STATUSES: InvoiceStatusEnum[] = [
  InvoiceStatusEnum.READY_TO_SEND_CHAPAR,
  InvoiceStatusEnum.READY_TO_SEND_MAHEX,
  InvoiceStatusEnum.READY_TO_SEND_GENERAL_EXPRESS,
  InvoiceStatusEnum.READY_TO_SEND_TIPAX,
];
