export enum ShippingServiceEnum {
  SHIPPING_SERVICE_CHAPAR_GROUND = 1 as number,
  SHIPPING_SERVICE_CHAPAR_AIR_CARGO = 2 as number,
  SHIPPING_SERVICE_CHAPAR_USING_POST = 3 as number,
  SHIPPING_SERVICE_CHAPAR_PLUS = 4 as number,
  SHIPPING_SERVICE_MODEMA_EXPRESS = 5 as number,
  SHIPPING_SERVICE_MAHEX_DOOR_TO_DOOR = 6 as number,
  SHIPPING_SERVICE_TIPAX = 7 as number,
}
